(defclass land     (card) ())
        (defclass island   (land) ())
        (defclass swamp    (land) ())
        (defclass forest   (land) ())
        (defclass plains   (land) ())
        (defclass mountain (land) ())
        (defclass nonbasic-land (land) ())

(defclass desert      (land) ())
(defclass gate        (land) ())
(defclass lair        (land) ())
(defclass locus       (land) ())
(defclass urzas       (land) ())
(defclass mine        (land) ())
(defclass power-plant (land) ())
(defclass tower       (land) ())
