;(defclass land     (card) ())
;        (defclass island   (land) ((name :initform "Island")))
;        (defclass swamp    (land) ((name :initform "Swamp")))
;        (defclass forest   (land) ((name :initform "Forest")))
;        (defclass plains   (land) ((name :initform "Plains")))
;        (defclass mountain (land) ((name :initform "Mountain")))
;        (defclass nonbasic-land (land) ())

(defparameter +island+   (make-card :types '(land) :name "Island"))
(defparameter +swamp+    (make-card :types '(land) :name "Swamp"))
(defparameter +forest+   (make-card :types '(land) :name "Forest"))
(defparameter +plains+   (make-card :types '(land) :name "Plains"))
(defparameter +mountain+ (make-card :types '(land) :name "Mountain"))

;(defclass desert      (land) ())
;(defclass gate        (land) ())
;(defclass lair        (land) ())
;(defclass locus       (land) ())
;(defclass urzas       (land) ())
;(defclass mine        (land) ())
;(defclass power-plant (land) ())
;(defclass tower       (land) ())
