(defparameter *colors*                     '(white blue black red green))
(defparameter *mana-symbols*               '(W     U    B             R   G))
(defparameter *hybrid-symbols*             '(W/U W/B U/B U/R B/R B/G R/G R/W G/W G/U))
(defparameter *phyrexian-mana-symbols*     '(W/P U/P B/P R/P G/P))
(defparameter *monocolored-hybrid-symbols* '(2/W 2/U 2/B 2/R 2/G)) 
(defparameter *mana-types*                 '(white blue black red green colorless))
(defparameter *mana-burn*                  'false) 
(defparameter *snow-symbol*                'S)

(defun floating ())
