(defgeneric become-monstrous   ())
(defgeneric become-renowned    ())
(defgeneric becomes-target     ())
(defgeneric blockers-declared  (attacking-player defending-player))
(defgeneric blocks             ())
(defgeneric championed         ())
(defgeneric changes-controller (obj old-controller new-controller))
(defgeneric changes-zone       (obj old-zone new-zone))
(defgeneric clashed                                        ())
(defgeneric combat-damage-done-once                        ()) 
(defgeneric counter-added      (spell))
(defgeneric counter-added-once (spell))
(defgeneric countered          (spell))
(defgeneric counter-removed    (spell))
(defgeneric cycled                   ())
(defgeneric damage-done              ())
(defgeneric dealt-combat-damage-once ())
(defgeneric destroyed                ())
(defgeneric devoured                 ())
(defgeneric discarded                ())
(defgeneric drawn                    ())
(defgeneric evolved            ())
(defgeneric exploited          ())
(defgeneric fight              ())
(defgeneric flipped-coin       ())
(defgeneric handler            ())
(defgeneric land-played        (player land))
(defgeneric life-gained        (player amount))
(defgeneric life-lost          (player amount))
(defgeneric loses-game         ())
(defgeneric new-game           ())
(defgeneric pay-cumulative-upkeep ())
(defgeneric pay-echo              ())
(defgeneric phase              ())
(defgeneric phase-in           ())
(defgeneric phase-out          ())
(defgeneric planar-dice        ())
(defgeneric planeswalked-from  ())
(defgeneric planeswalked-to    ())
(defgeneric sacrificed         ())
(defgeneric srcy               ())
(defgeneric searched-library   ())
(defgeneric set-in-motion      ())
(defgeneric shuffled	       ()) 
(defgeneric spell-ability-cast ()) 
(defgeneric taps-for-mana      ())
(defgeneric taps               ())
(defgeneric transformed        ())
(defgeneric turn-face-up       ())
(defgeneric type               ())
(defgeneric unequip            ())
(defgeneric untaps             ())
(defgeneric vote               ())
(defgeneric waiting            ())
(defgeneric enters-battlefield (card))
