(defun get-priority ()
        (print "priority>"))

        (defun untap-step ()
	        (print "Untap Step")
                ;(phasing)
                ;(untap-all))
	        nil)
        (defun upkeep-step ()
	        (print "Upkeep Step")
                ;(triggers)
                (get-priority)
	        nil)
        (defun draw-step ()
	        (print "Draw Step")
                ;(draw active-player 1)
                ;(triggers)
                (get-priority)
	         nil)

(defun beginning-phase ()
        (print "Beginning Phase")
	(untap-step)
	(upkeep-step)
	(draw-step))

(defun main-phase (which)
        (print "Main Phase")
	(print which)
        ;(play-land))
        nil)

(defun combat-phase ()
  (print "Combat Phase")
  (beginning-of-combat-step)
  (declare-attackers-step)
  (declare-blockers-step)
  (combat-damage-step)
  (end-of-combat-step))


        (defun beginning-of-combat-step ())
        (defun delare-attackers-step ())
        (defun declare-blockers-step ())
        (defun combat-damage-step ())
        (defun end-of-combat-step ())

(defun end-step ()
	(print "End Step"))

(defun cleanup-step ()
	(print "Cleanup Step"))

(defun ending-phase ()
        (print "Ending Phase")
	(end-step)
	(cleanup-step))

(defun turn ()
	(beginning-phase)
	(main-phase 1)
	(combat-phase)
	(main-phase 2)
	(ending-phase))

(defun main ()
        (turn))
