(defclass ability           (mtg-object) ())
(defclass triggered-ability (ability) ())
(defclass activated-ability (ability) ())
(defclass loyalty-ability   (activated-ability) ())
(defclass mana-ability      (activated-ability) ())
(defclass static-ability    (ability) ())
(defclass keyword-ability   (ability) ())
(defclass evasion-ability   (ability) ())
